### ISSUE TITLE
oscillations - visual - all words

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#25]
- pipeline implementation. Which pipeline? Which dependent key functions?
- pipeline documentation. Are the scripts sufficiently verbose to understand what is going on? Is there separate documentation?
- single subject results computation. Where are these stored? Tick off only when all subjects have been run with a consistent version of the pipeline.
- group result computation (if applicable). Which script has been used? Where is the script located? Where are the results located?
- results visualization. Which script has been used? Where is the script located? Where are the figures located?

**Comment by nihll** [comment]
The results are finalised, this analysis is complete.
pipeline implementation: mous_bfica_pipeline using the sections 'doecg', 'dodss', 'dofreq' and 'dosource_contrast'  
Also required: mous_bfica_sourcedata_combinefreq to combine all frequencies within one range (low, medium, high) into a file
single subject results computation: all subjects run using the same pipeline above, and stored in /project/3011020.09/MEG/VXXX/bfica. 
Group-level results using MOUS/meg/analysis_functions/mous_bfica_sourcestatistics 
Result in: /project/3011020.09/nielam/groupresults/bfica/visual/sentseq
Visualization on cortical sheet, this required interpolating from 3d volumetic data to the 2d cortical sheet, and visualizing in workbench.
mous_bfica_surfaceandparcellation.m
