### ISSUE TITLE
Determining word onsets for some of the words in the auditory stimuli

### ISSUE THREAD

**Issue by annhul** [schoffelen/MOUS#48]
I got the impression that there was general agreement that we should ask RAs to mark the onset times of all words also in the auditroy condition. In priniciple this is not a bad idea but it might be good to first evaluate if this is the time to do it and whether it is worth the effort. 
a) Marking the word onset in co-articulated speech is extreamly labourous. I would estimate about 5 min/word and if we assume that our 180 sentences with say 13 words each that is already 195 hours (+ the word lists which are faster to do as they don't have co-articularion).And this needs to be done by at least 2 evaluators. We shoudl think carefully before requesting this much RA time.
b) At least in meg, the situation is also different between visual and auditory with respect to the signal. In the visual the signal returns to baseline between each word which it does not in the auditory. This is why we originally set out to only focus on the target words.
c) I am not in favour of changing our planned analysis approach before we have doens what we originally planned, i.e. compare traget words, and evalute if this comparison answers our research question. We started analysing all words in the visual as JM was consercn about snr, from that grew the parametric word order test. This test admittedly adds something unique to the research question, but as the target words are systematically spread out in the sentence this approach might be done on targets only. Remember that target words are controlled for a number of important psycholinguistic factros such as frequency and preceeding word which we know will also affect the signal greatly. Thus, what we migh gain in snr by using all words we might loose in snr by variation in word duration, word frequency, baseline variation etc.

So much suggestion, as it has been all along, is to first finnish all analysis we can with present information, as planned and then evaluate if coding for all words will give the additional information that is worth the effort of extracting them.

**Comment by schoffelen** [comment]
It seems the RA have more or less finished the job for the sentences. I have asked them to continue with the word lists.

**Comment by schoffelen** [comment]
continue this issue on #78
