### ISSUE TITLE
compare MEG response to audio and visual input

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#64]
As discussed during today's (20140902) meeting with Annika and Julia, I will push the comparison between the audio and visual results.

First step to take is to ensure that we have the data processed as far as possible according to the latest standards. It seems for the visual data that there's some stuff in Annika's folder on /project/3011020.09/ (but using time axes starting from -0.1 and ending at 1, and on the MEG folder the audio preprocessed data is present for 101 subjects, but the respective single word averages (firstword and target) are incomplete/absent. The latest version of the preprocessed data for the visual subjects dates from the end of may, whereas the ERFs in Annika's folder are from October last year... the processed audio data is from ~april/may and later subjects have not yet been processed.

TO DO:
-process all audio subjects as far as possible with mous_preprocessing_pipeline (-02-10)
-process all audio subjects with mous_erf_pipeline for main effect, + separate allwords, firstword and targets.
-process all visual subjects with mous_erf_pipeline for main effect for firstword and targets only (not allwords).

**Comment by schoffelen** [comment]
TO DO:
~~-process all audio subjects as far as possible with mous_preprocessing_pipeline (-02-10)~~
~~-process all audio subjects with mous_erf_pipeline for main effect, + separate allwords, firstword and targets.~~
~~-process all visual subjects with mous_erf_pipeline for main effect for firstword and targets only (not all words).~~

**Comment by annhul** [comment]
@schoffelen 
Do you have group level statistics for the auditory target words I could look at? I tried to run 
rootdir = '/project/3011020.09/MEG';
[subj,s] = setdiff(mous_db_getfilename('allA','subjectname'), mous_db_getfilename('bad','subjectname'));   
[f,exist_data] = mous_db_getfilename(subj,['meg_processed_{_mne_target_02-10_sent}'],0 , rootdir);
subj   = subj(exist_data);
Nsubj   = numel(subj);
suffix  = 'meg_processed_{_mne_target_02-10_sent}';
[stat,sent,seq,datsent,datseq] = mous_mne_groupanalysis(subj, suffix, rootdir); 

It loads in the data and proceedes to the permutations but after completing they I get the following error. Something to do with the wrong matlab library perhaps?

computing statistic 1000 from 1000

Error using spm_bwlabel
spm_bwlabel: CONN must be 6, 18 or 26

Error in clusterstat (line 183)
      [posclusobs, posnum] = spm_bwlabel(tmp, 2*numdims);

Error in ft_statistics_montecarlo (line 355)
  [stat, cfg] = clusterstat(cfg, statrand, statobs);

Error in ft_sourcestatistics (line 202)
  [stat, cfg] = statmethod(cfg, dat, design);

Error in mous_mne_groupanalysis (line 171)
stat = ft_sourcestatistics(cfg,sent{:},seq{:});
