### ISSUE TITLE
provide a framework for consistent visualization of results

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#74]
To get a more or less state-of-the-art visualization of the results, it was agreed at Nov 3 to present the (cortical) results on the non-inflated cortical sheet. For the MNE data this comes quite naturally, for the oscillations MEG and fMRI data, some work needs to be done.
JM's suggestion was to use HCP workbench for visualisation. Advantage: state-of-the-art, uses openGL graphics for slick displays, allows for easy overlays of different functional maps etc. Disadvantage: is not very well documented and a bit quirky in its usage + requires a special file format (cifti) to work.

To do:
- @JuliaUdden point me to a script of how to get from a SPM-file to a freesurfer wfile.
- @nihll discuss how to display the oscillations results.

**Comment by JuliaUdden** [comment]
The path to wb_view changed to from hcp-workbench_1.0 to hcp-workbench/1.0, hence use:

export PATH=$PATH:/opt/hcp-workbench/1.0/bin_rh_linux64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hcp-workbench/1.0/libs_rh_linux64
