### ISSUE TITLE
implement an analysis framework that links computational model output to the electrophysiological data

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#82]
As per the following e-mail discussion:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Dear all,

Today I had a meeting with Antal van den Bosch, who has developed methods
derived from information theory to characterize sentences and sequences in a more
formal way.

Now that we have all the data, the next step is to characterize our stimulus materials
in a more quantitative and exact way. Antal will do this.

To realize this I need the sentence and sequence materials in a well-organized way,
including the recent annotations that Nietzsche and I made.

Can someone send this to me.

To compare our results with Tineke's, we will also run these analyses
on her stimulus materials. Tineke can you send me the materials of your study.

best wishes,

Peter
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++

Dear Peter,

I think this is an excellent plan. Note that Roel (in CC) and I have been playing around with the output of Antal’s parser in combination with MEG in our ‘Streams’ project. Due to logistic constraints this project is not as far as we hoped it to be (we have acquired ~10 subjects worth of data), and we still have to figure out the best way of linking the electrophysiological data to the model output. It could be that with visual word presentation the temporal link is better defined, allowing for a more straightforward data analysis (e.g. binning the individual words according to the output values along one of the dimensions of Antal’s data, which is hardly possible with the continuous audio signal). 
As a side note (not related to MOUS) I should mention that I have managed to devote some more time to streams recently, and rather than going for the quick and dirty approach, decided to take it slow. I have started with quantifying the entrainment of the brain to the audio stimulus and initial results look very promising, in the sense that each subject’s data is of sufficient quality to find spatially and spectrally specific entrainment at different frequencies (~1 Hz and around 4 Hz).
Shall I cut you out as the middle man for efficiency, and send the text-material of MOUS to Antal directly?

My suggested way forward here would be:
-Nietzsche sends Peter and JM the annotated stuff (is this much work or could this be done by today?). 
-JM sends Antal the text material (I guess he doesn’t need Nietzsche’s annotations, so I can just write text file from the stimulus material that I have represented as a mat-file). (I can do this today).
-Antal parses the data. (hopefully quickly).
-JM writes the necessary glue-code to be able to read in the model results into matlab (using code he already has developed for streams). (once the data is back it can be done in a week).

Then:
-Design an initial analysis pipeline to link the biological data to the model data (who? by when?)
-Write the necessary code (who? by when?)
-Do the analysis (who? by when?)

Once we have a meaningful pipeline in place we can subject Tineke’s data to a similar analysis strategy. This would probably mean that Tineke needs to dust off her data archive to find an easy entry point into the data.

Do we have a plan?

Best wishes,

Jan-Mathijs

**Comment by schoffelen** [comment]
I manually corrected the sentence material, according to my understanding of syntactic trees. This meant that the majority of the sentences needed to be corrected, unfortunately. TODO: let peter or antal check a few of these, to see whether I did it right.

I started working on the following condition definitions:
-for sentences: a word pointing to its (local) syntactic head further away in the sentence, and a word pointing to its (local) syntactic head earlier in the sentence.
-for sequences: the dependency number per word was taken from the corresponding sentence equivalent word. 

The idea is now that sentences versus sequences is relatively comparable, because the overall stimulus material is matched in terms of word type and dependency values across the conditions. Yet, the ordinal word position histograms are not really compatible, so an additional stratification step was done on the ordinal word positions, to make these equal.
The more interesting comparison would then be the two dependency conditions compared (after stratification for ordinal word position). Yet, the potential confound is the non-match in word type (because on average forward pointing words can be different in terms of word class from backward pointing words). So, in order to partially alleviate this I would suggest to compute an interaction contrast between sentences and sequences.

**Comment by schoffelen** [comment]
After thinking this over I think we should classify the words according to whether they are open or closed class. Laura has marked all stimulus material, and @nihll has some code to read it out of the excel file.

TO DO:
- @nihll make this code available in git and ensure that it works for everyone.
- identify the auxiliary verbs and treat them as a special class.
- stratify the above comparisons (see the other comments) according to word class, OR use the open class words only

**Comment by schoffelen** [comment]
TO DO:
~~- @nihll make this code available in git and ensure that it works for everyone.~~  -> has done this
- identify the auxiliary verbs and treat them as a special class.
- stratify the above comparisons (see the other comments) according to word class, OR use the open class words only

**Comment by schoffelen** [comment]
@JuliaUdden @nihll @annhul there is now a directory in /project/3011020.09/MEG: misc that I created to contain general purpose data for the analysis. It now contains a file mous_stimuli, which is a struct-array (1 struct for each of the stimuli), that contains basic information about the stimuli.

**Comment by schoffelen** [comment]
I pushed a function to mous/meg/trialfun, called mous_stimuli_addstack, it basically uses (cleaned up) code from Julia, that adds information with respect to a 'push-down stack' to the stimuli struct-array. I don't fully understand the philosophy yet. I updated the stimuli file on /project/3011020.09/misc
Note that I renamed some of the fields as named by Julia, because I think this would make sense.
Noet also, that the stack_depth vector (which Julia called stack_depth_empirical) is now also available as a field of stimuli, i.e. stimuli(k).stack_depth directly returns a vector, so there's no need to extract it as [stimuli(k).words.stack_depth], where each word's stack_depth is stored as a separate scalar.
If you run the function, it produces a histogram of the maximum stack depth for the RC+ and RC- sentences, showing that there is indeed a difference in the distribution.

**Comment by schoffelen** [comment]
As another update, there has been a meeting with Antal yesterday, and the outcome was that my initial division of individual words, based on forward vs. backward pointing dependencies was not so stupid after all. The refinement here is that it does not make sense to look at the forward pointing words, because the brain does not know yet whether it will be a word with a long or short dependency.
Making a contrast between long and short range dependencies for backward pointing words was now considered to be a viable strategy. This is therefore what I will do. Probably I need to first kind of balance the words according to wordtype and possibly lexical frequency.

**Comment by schoffelen** [comment]
To be sure that the relevant other people are reading this: @JuliaUdden @annhul @nihll I explicitly now add you to this issue :-).

**Comment by JuliaUdden** [comment]
Note that I have only so far debugged the code for one sentence. I send the
code more to show the philosophy. The philosophy will probably become more
clear in Wednesday's presentation and also when I get around to write a
paragraph on the approach. Thanks for the maximum stack depth histogram! I
will show it on Wednesday. To get an overview of the global measure per
sentence, it will also be good to determine where in the sentences the
maximum depth is. It is intended also as a local measure, for the MEG data.
Note that the stack on word x actually rather describes the complexity for
processing word x+1 then word x itself.

**Comment by schoffelen** [comment]
For further development of the code, please work on the version in the git repository, and not on your local copy.

**Comment by JuliaUdden** [comment]
I looked at the code now - really clean, thanks! Will study it line by line
later. I also saw your question on the implementational choice of pushing
the word vs pushing the depind.I am actually using depjump instead of
depind in the computation, so in principle, as the code is now, the words
could be pushed and that would be more intuitive. I can however imaging
that if we want to change the model in future steps, the depind might be
useful. I am fine with either.

**Comment by schoffelen** [comment]
We can worry about exact implementation details later. Do you have a literature reference for dummies that I could look at?

**Comment by schoffelen** [comment]
I added the computation of a histogram for the ordinal word position where the stack_depth is highest

**Comment by JuliaUdden** [comment]
Not really, this one is the closest I can think of at the point:
http://www.ncbi.nlm.nih.gov/pubmed/22452530 . Right now, the model does not
include a real stack, but a random access memory, but it is prepared to
also be able to test a model where there is one or several real push down
stack(s),

**Comment by JuliaUdden** [comment]
Thanks! I pulled now again but I got the answer that there were no updates,
so I can't find the ordinal word position histogram right now. Am I missing
some github-related knowledge perhaps?

**Comment by schoffelen** [comment]
nope; my bad. I forgot to git push. Did so just now. Please pull again.

**Comment by schoffelen** [comment]
@JuliaUdden still suffered from the fact that the dependency indices of stimuli 248 and 266 did not yield a 'valid' tree as defined with the matlab-function treeplot. Although I don't need it for my analyses at the moment, I have updated mous_stimuli to the best of my knowledge, so that none of the stimuli now causes treeplot.m to choke.

**Comment by JuliaUdden** [comment]
Thanks for a fast response.

**Comment by JuliaUdden** [comment]
I am looking for the total duration of the audio files, to use it in the auditory complexity fMRI analysis. I would like to clarify what the timinginfo in mous_stimuli, e.g. stimuli(n).timinginfo  stands for. Is it the onset of each word relative to the onset of the file (in seconds), plus a last NaN slot which displays the total duration of the file? Is word by word onset the work that the RAs did, coding onsets of individual words?

**Comment by JuliaUdden** [comment]
@schoffelen, @nihll

**Comment by schoffelen** [comment]
indeed.

**Comment by JuliaUdden** [comment]
Thanks.
