### ISSUE TITLE
Adjust oscillations (bfica) pipeline to try to improve SnR for gamma results

### ISSUE THREAD

**Issue by nihll** [schoffelen/MOUS#83]
There are two approaches for improving SnR in the gamma analysis:

1.  Don't remove ECG at the start of bfica pipeline.   Using the ECG to remove low frequency components, can also lead to adding noise at higher frequencies, therefore, we will not use the "remove ECG" step in the pipeline

2. Compute spatial filters from baseline to 0.5s  (non time varying filter), as opposed to a unique spatial filter for each time point.

**Comment by schoffelen** [comment]
@nihll based on your verbal report these things did not make an appreciable difference. Would you want to show me some results of the comparison, or are you happy to close this issue? Perhaps it is good to document your findings (does not need to be long) here.

**Comment by nihll** [comment]
-	Action point #1:   do not remove EKG signal  (only necessary for connectivity analyses)
-	Action point #2:   calculate a non-time-varying spatial filter 
-	For both actions points, Nietzsche also tried using a modified version of the t-test which is less sensitive to outlier
o	None of the approaches improved the results  (stat.stat is different for the 2 approaches)
	Keeping EKG:  40-68Hz  p  = 0.01;   84 – 100 Hz  p = 0.8    
	Non-time-varying spatial filter:   p  = 0.001 (occipital cortex);   84 – 100 Hz  p = 0.16
