### ISSUE TITLE
ft_sourcestatistics 

### ISSUE THREAD

**Issue by annhul** [schoffelen/MOUS#84]
ft_sourcestatistics does not recognise the event-related mne' as source level data or something along that line @schoffelen

**Comment by schoffelen** [comment]
error occurs in ft_selectdata (getselection_pos), because 'not implemented'
-file bugzilla bug
-upload some test data
-fix it
-report it here.

**Comment by schoffelen** [comment]
error occurs in ft_selectdata (getselection_pos), because 'not implemented'
~~-file bugzilla bug~~
-upload some test data
-fix it
-report it here.

**Comment by schoffelen** [comment]
error occurs in ft_selectdata (getselection_pos), because 'not implemented'
~~-file bugzilla bug~~
~~-upload some test data~~
-fix it
-report it here.


I created some test data, but cannot reproduce the bug, in other words: it just works for me. Can you check whether you used an up-to-date version of FieldTrip, and point me to the script that you used to produce the error?

**Comment by annhul** [comment]
I use the ft version that I get by using 
addpath /home/common/matlab/fieldtrip 
ft_defaults
That should be the latest as far as I know.
The code that produces the error is 
/project/3011020.09/annhul/analyses/analysis20150414_3.m

**Comment by schoffelen** [comment]
And you are sure that you are not overloading the FT version from /home/common with a stale version that gets shipped with  SPM? :-)

**Comment by annhul** [comment]
yes, I have commented out the entire spm part of my startup.m file. It only contains a ft path ft_defaults and some paths to my home dir. Have a look yourself ~/language/annhul/matlab/startup.m

**Comment by annhul** [comment]
is matlab2014a a problem?

**Comment by schoffelen** [comment]
I don't know, never worked with it

**Comment by annhul** [comment]
I can try another version..which do you use?

**Comment by schoffelen** [comment]
I typically use 2013b

**Comment by annhul** [comment]
tried with matlab2013b but still get an error. I also double checked the ft version 
>> which ft_checkdata
/home/common/matlab/fieldtrip/utilities/ft_checkdata.m
>> which ft_sourcestatistics.m
/home/common/matlab/fieldtrip/ft_sourcestatistics.m

That is the path to the most recent ft right?

**Comment by schoffelen** [comment]
Yes, it is. I'll have a look at it. (it could be that my turbo version knows something that the official version does not know).

**Comment by schoffelen** [comment]
I placed a version of your script that runs on /project/3011020.09, called analysis20150414_3JM.m
Could you remove it once you have copied it into your own directory?

**Comment by annhul** [comment]
Done. Seems to work for me as well. Thank you.

**Comment by annhul** [comment]
I get the same type of  error when trying to run group statistics on parcellated data using ft_timelockstatistics. That is the approach to go on with parcel data, no?

 As far as I can figure out timelock data is defined by the field labels and time, both of which I have added. You can (hopefully) replicate the problem by running /project/3011020.09/annhul/analyses/analysis20150429_1.m

**Comment by schoffelen** [comment]
Big sigh. 
What do you mean with 'I get the same type of error'?

**Comment by annhul** [comment]
Sorry.
stat = ft_timelockstatistics(cfg, dat1, dat2);
Error using ft_checkdata (line 464)
This function requires timelock data as input.

Error in ft_timelockstatistics (line 82)
  varargin{i} = ft_checkdata(varargin{i}, 'datatype', 'timelock', 'feedback', 'no');

**Comment by schoffelen** [comment]
can you please call the function as it should be called:

stat = ft_timelockstatistics(cfg,dat1{:},dat2{:});

This was the change I needed to make for ft_sourcestatistics to run, too.

**Comment by annhul** [comment]
Well aren't you clever! Thank you! :)
