### ISSUE TITLE
mous_write_cifti_dense: does not produce files that can be opened in wb_view

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#88]
I assume that this is what @annhul contacted me about by e-mail. I suggest to follow this up here

**Comment by schoffelen** [comment]
I pushed an updated mous_write_cifti_dense. It should work now.

Please use some variants on the following code. Especially the scaling is relevant, because the wb_view developers have not considered the possibility that the numbers-to-be-plotted are very small.

##############################################################
load /project/3011020.09/annhul/results/Vis_group102_sentSeq_clusterstat.mat



filename = 'testcifti';
test = sent{1,1};
test.avg = rmfield( test.avg , 'pow' ) ;
test.avg = datsent;
test     = rmfield(test, {'outside' 'dim'});

% this scaling needs to be done
test.avg = test.avg.*(10.^(-1-round(nanmean(log10(test.avg(:))))));

mous_write_cifti_dense(filename, test, 'parameter' , 'avg', 'time' , test.time);

**Comment by annhul** [comment]
The matlab part works but I still haven't figured out how to display the created file in wb. What I have done so far is loaded the template spec file and with open file loaded the newly created surf.gii. However it is not in the overlays and in the Manage Data Files it is marked for display (and I don't know how to change this). 
![screenshot20150911-1](https://cloud.githubusercontent.com/assets/1788169/9809499/63d5fd2c-5871-11e5-9069-168a4419e768.png)

**Comment by schoffelen** [comment]
You don't necessarily need the surf.gii files. These only contain the topologies of the cortical sheet. You need to load in the dtseries.nii file. The wb_view manual (admittedly, it's a bit shitty) will probably be able to point you to how to visualize it further (hint: you need to check one of the boxes at the left of the 'overlay toolbox' panel (in the layers-tab, i.e. at the lower left of the figure you attached to this bug).

**Comment by annhul** [comment]
The wb_manual seems to be able to help me once I manage to the get my data into the overlays, which I currently don't know how to do. Open File and selecting the dtseries does not automatically put it in the overlays...

**Comment by schoffelen** [comment]
![screen shot 2015-09-11 at 10 29 39 am](https://cloud.githubusercontent.com/assets/1517611/9810332/2d7aeaa4-5870-11e5-8fb9-2f8a249dddf8.png)

**Comment by schoffelen** [comment]
![screen shot 2015-09-11 at 10 29 56 am](https://cloud.githubusercontent.com/assets/1517611/9810339/365181f6-5870-11e5-92e1-4ed0a29d9fea.png)

**Comment by schoffelen** [comment]
![screen shot 2015-09-11 at 10 30 17 am](https://cloud.githubusercontent.com/assets/1517611/9810344/3d47126e-5870-11e5-970f-d69fb3fffca8.png)

**Comment by schoffelen** [comment]
![screen shot 2015-09-11 at 10 30 34 am](https://cloud.githubusercontent.com/assets/1517611/9810348/46591604-5870-11e5-80c3-087c69c96c41.png)

**Comment by annhul** [comment]
Works.
