### ISSUE TITLE
wb for vizualization of evoked data

### ISSUE THREAD

**Issue by annhul** [schoffelen/MOUS#89]
I am having problems with setting the scale to my liking. If using a jet scale (the darker the color the higher values) , the scale sets the darkest blue color at zero though I would like it to go from -0.06 to 0.06 (see screen shot).  @schoffelen 

![image](https://cloud.githubusercontent.com/assets/1788169/10095952/44828264-6376-11e5-8f84-6864cc6c713d.png)

**Comment by schoffelen** [comment]
I assume you know about the menu that allows you to play around with thresholds, color ranges and color maps? I think that there are sufficient degrees of freedom there to get what you want. You should be able to color code the negative values as well (provided there are negative values in your functional maps :o) ).

**Comment by annhul** [comment]
Yes I am, and I can it to work on the Psych-no-none color scale  (that give lighter color the higher the value) but not using the jet scale...
![image](https://cloud.githubusercontent.com/assets/1788169/10097868/0975a480-6385-11e5-9de6-d7b1f70dda1f.png)

**Comment by schoffelen** [comment]
I am a bit puzzled by the distribution of the values. Is this the same for the matlab variable that you use, prior to exporting it to a cifti file?

**Comment by annhul** [comment]
I think the histogram is summing the observations across all time points  because I have the fixed scale option set.

**Comment by schoffelen** [comment]
but why is there a gap between -0.03 and 0.03, and why are the negative values so 'sticky'.

**Comment by annhul** [comment]
Because the data is masked before transforming it to nifti.

**Comment by schoffelen** [comment]
I don't think that this is still an issue. Closing for now.
